[symlinks]
"nvim/after/rust-colors/lua/init.lua" = "/Users/VCY1YF8/.config/nvim/after/rust-colors/lua/init.lua"
"nvim/init.lua" = "/Users/VCY1YF8/.config/nvim/init.lua"
"nvim/lua/.DS_Store" = "/Users/VCY1YF8/.config/nvim/lua/.DS_Store"
"nvim/lua/sebs/cmds.lua" = "/Users/VCY1YF8/.config/nvim/lua/sebs/cmds.lua"
"nvim/lua/sebs/init.lua" = "/Users/VCY1YF8/.config/nvim/lua/sebs/init.lua"
"nvim/lua/sebs/lazy.lua" = "/Users/VCY1YF8/.config/nvim/lua/sebs/lazy.lua"
"nvim/lua/sebs/plugins/bufferline.lua" = "/Users/VCY1YF8/.config/nvim/lua/sebs/plugins/bufferline.lua"
"nvim/lua/sebs/plugins/colors.lua" = "/Users/VCY1YF8/.config/nvim/lua/sebs/plugins/colors.lua"
"nvim/lua/sebs/plugins/crates.lua" = "/Users/VCY1YF8/.config/nvim/lua/sebs/plugins/crates.lua"
"nvim/lua/sebs/plugins/gitsigns.lua" = "/Users/VCY1YF8/.config/nvim/lua/sebs/plugins/gitsigns.lua"
"nvim/lua/sebs/plugins/harpoon.lua" = "/Users/VCY1YF8/.config/nvim/lua/sebs/plugins/harpoon.lua"
"nvim/lua/sebs/plugins/init.lua" = "/Users/VCY1YF8/.config/nvim/lua/sebs/plugins/init.lua"
"nvim/lua/sebs/plugins/lsp-icons.lua" = "/Users/VCY1YF8/.config/nvim/lua/sebs/plugins/lsp-icons.lua"
"nvim/lua/sebs/plugins/lsp-saga.lua" = "/Users/VCY1YF8/.config/nvim/lua/sebs/plugins/lsp-saga.lua"
"nvim/lua/sebs/plugins/lsp.lua" = "/Users/VCY1YF8/.config/nvim/lua/sebs/plugins/lsp.lua"
"nvim/lua/sebs/plugins/lualine.lua" = "/Users/VCY1YF8/.config/nvim/lua/sebs/plugins/lualine.lua"
"nvim/lua/sebs/plugins/mason.lua" = "/Users/VCY1YF8/.config/nvim/lua/sebs/plugins/mason.lua"
"nvim/lua/sebs/plugins/spellsitter.lua" = "/Users/VCY1YF8/.config/nvim/lua/sebs/plugins/spellsitter.lua"
"nvim/lua/sebs/plugins/telescope.lua" = "/Users/VCY1YF8/.config/nvim/lua/sebs/plugins/telescope.lua"
"nvim/lua/sebs/plugins/treesitter.lua" = "/Users/VCY1YF8/.config/nvim/lua/sebs/plugins/treesitter.lua"
"nvim/lua/sebs/plugins/which-key.lua" = "/Users/VCY1YF8/.config/nvim/lua/sebs/plugins/which-key.lua"
"nvim/lua/sebs/remap.lua" = "/Users/VCY1YF8/.config/nvim/lua/sebs/remap.lua"
"nvim/lua/sebs/set.lua" = "/Users/VCY1YF8/.config/nvim/lua/sebs/set.lua"

[templates]
